name: cpm-first-grid
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.7787234
  brandStrength: 0.2914894
  lightness: 0.5914894
  brandColors:
    - '#3A66BC'
    - '#0C0F14'
    - '#B3E1FF'
    - '#424B6E'
    - '#FFFBE0'
  rhythmicContrast: 0.3
typography_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2680851
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
