name: cpm-first-grid
favicon: null
layout_spectrum: 0.7322719662915915
typography_spectrum: 0.9974872563034296
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.19823770294897258
  lightness: 0.47879045526497066
  saturation: 0.9901164218317717
  rhythmicContrast: 0.45562782417982817
purpose: []
