favicon: null
name: cpm-first-grid
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5510638
  brandStrength: 0.8489361
  lightness: 0.8489361
  brandColors:
    - '#3A66BC'
    - '#0C0F14'
    - '#B3E1FF'
    - '#424B6E'
    - '#FFFBE0'
  rhythmicContrast: 0.5638298
typography_spectrum: 0.19717
layout_spectrum: 0.51604
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
