analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3
  brandStrength: 0.7489362
  lightness: 0.7021276
  brandColors:
    - '#3A66BC'
    - '#0C0F14'
    - '#B3E1FF'
    - '#424B6E'
    - '#FFFBE0'
  rhythmicContrast: 0.593617
typography_spectrum: 0.7340425
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.8510638
favicon: null
name: cpm-first-grid
